apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    service: order
spec:
  selector:
    service: order
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    service: order
spec:
  replicas: 3
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
    spec:
      containers:
      - name: order
        image: order
        env:
          - name: APPLICATION_PORT
            value: "50051"
          - name: ENV
            value: "prod"
          - name: DATA_SOURCE_URL
            value: "root:s3cr3t@tcp(mysql:3306)/orders?charset=utf8mb4&parseTime=True&loc=Local"
          - name: PAYMENT_SERVICE_URL
            value: "payment:50051"
          - name: MONGO_ADDRESS
            value: '["mongo.default.svc.cluster.local:27017"]'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: adminuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password123

        ports:
          - containerPort: 50051
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: order
spec:
  rules:
    - http:
        paths:
          - path: /Order
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 50051
  tls:
    - hosts:
        - ingress.local
      secretName: order-tls
