apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec:
  clusterIP: None
  selector:
    service: payment
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels:
        service: payment
    spec:
      containers:
      - name: payment
        image: payment
        env:
          - name: APPLICATION_PORT
            value : "50051"
          - name: ENV
            value: "prod"
          - name: DATA_SOURCE_URL
            value : "root:s3cr3t@tcp(mysql:3306)/payments?charset=utf8mb4&parseTime=True&loc=Local"
          - name: MONGO_ADDRESS
            value:  '["mongo.default.svc.cluster.local:27017"]'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: adminuser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: payment
spec:
  rules:
    - http:
        paths:
          - path: /Payment
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 50051
  tls:
    - hosts:
        - ingress.local
